### ISSUE TITLE
Mopidy Server connection does not seem to work

### ISSUE THREAD

**Issue by tekdru** [cristianpb/muse#17]
In the Settings of version 0.0.17. Trying to connect to a "Mopidy Server" does not work. It only brings up the spinning wheel.

**Comment by cristianpb** [comment]
Hi @tekdru 
I had the same problem when testing on different environments, but I realized that I needed to add the current origin url to the mopidy configuration.

You can find more information here: https://docs.mopidy.com/en/latest/ext/http/#confval-http-allowed_origins

So I think the problem is not completely related with Muse.

**Comment by tekdru** [comment]
Ok Thank you!

**Comment by cristianpb** [comment]
Hope now it works for you. I will close this thread but feel free to reopen this issue or open a new one if you have another problem.
